version: '3.8'
services:
  db:
    image: postgres
    environment:
      TZ: "UTC"
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - syncIn
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
networks:
  syncIn:
    driver: bridge