version: '3.8'
services:
  db:
    image: postgres
    env_file:
      - .env
    environment:
      TZ: "UTC"
      POSTGRES_DB: 'kursova'
      POSTGRES_USER: 'max'
      POSTGRES_PASSWORD: '12345'
    ports:
      - "5432:5432"
    networks:
      - syncIn
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    networks:
      - syncIn
  rabbitmq:
    image: rabbitmq:3.11.5-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "root"
      RABBITMQ_DEFAULT_VHOST: "root"
      RABBITMQ_QUEUE_NAME: "my_queue"
      RABBITMQ_EXCHANGE_NAME: "my_exchange"
volumes:
  db-data:
  rabbitmq-data:
networks:
  syncIn:
    driver: bridge
